import type { Metadata } from "next";
import localFont from "next/font/local";
import "normalize.css";
import "../styles/global.scss";
import Header from "../ui/Header/Header";

const tacticSans = localFont({
  src: "../styles/fonts/TacticSans-Reg.woff",
  variable: "--font-tactic-sans",
  weight: "400",
});
const tacticSansMed= localFont({
  src: "../styles/fonts/TacticSans-Med.woff",
  variable: "--font-tactic-sans-med",
  weight: "500",
});
const tacticSansBold = localFont({
  src: "../styles/fonts/TacticSans-Bld.woff",
  variable: "--font-tactic-sans-bold",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Maximum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tacticSans.variable} ${tacticSansMed.variable} ${tacticSansBold.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
