import type { Metadata } from "next";
import localFont from "next/font/local";
import "normalize.css";
import "../styles/global.scss";
import Header from "../ui/header/Header";

const tacticSansFont = localFont({
  src: [
    {
      path: "../styles/fonts/TacticSans-Reg.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../styles/fonts/TacticSans-Med.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../styles/fonts/TacticSans-Bld.woff",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Maximum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tacticSansFont.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
