import type { Metadata } from "next";
import localFont from "next/font/local";
import "normalize.css";
import "../styles/global.scss";
import Header from "../ui/header/header";

const tacticSans = localFont({
  src: "../styles/fonts/TacticSans-Reg.woff",
  variable: "--font-tactic-sans",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Maximum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tacticSans.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
